name: Development

on:
  pull_request:
    branches: devel

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4.0.4
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run formatter check
      run: npx prettier --check "./src/"

    - name: Run tests
      run: CI=true npm test

    - name: Build
      run: npm run build

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      working-directory: ./terraform/environments/devel
      env: 
        AWS_ACCESS_KEY_ID:        ${{ secrets.TF_AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY:    ${{ secrets.TF_AWS_SECRET_KEY}}

    - name: Terraform init
      working-directory: ./terraform/environments/devel
      run: terraform init

    - name: Terraform plan
      working-directory: ./terraform/environments/devel
      run: terraform plan

    - name: Terraform apply
      working-directory: ./terraform/environments/devel
      run: terraform apply -auto-approve
      